CC=gcc
CFLAGS=-o
matrix output:
	$(CC) matrix_output.c $(CFLAGS) matrix_output

	$(CC) reverse_data.c $(CFLAGS) reverse_data

	$(CC) snail.c $(CFLAGS) snail
	
	$(CC) upper_and_lower_triangles.c $(CFLAGS) u_l_triangles
